### ISSUE TITLE
Repo is kapot door Sentiment

### ISSUE THREAD

**Issue by dqos** [minorsmart/sep2017#5]
@witusj graag de volgende map verwijderen:
https://github.com/minorsmart/sep2017/tree/master/proj/Sentiment

Ik kan helemaal niets meer met de repo op Windows, waarschijnlijk omdat bepaalde bestanden in die map eindigen met ?. Ik zal daarna Sentiment opnieuw pushen via Windows, waarschijnlijk ligt dit aan macOS/Windows.

`error: unable to create file proj/Sentiment/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/docs/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/docs/g/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/docs/html/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/docs/js/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/01-web/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/02-db/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/03-en/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/04-search/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/05-vector/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/05-vector/corpus/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/06-graph/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/07-canvas/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/08-server/01-basic/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/08-server/01-basic/static/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/08-server/02-api/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/08-server/03-wiki/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/08-server/03-wiki/data/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/08-server/04-db/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/08-server/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/examples/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/test/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern-master/test/corpora/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/db/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/graph/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/server/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/server/cherrypy/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/server/cherrypy/cherrypy/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/server/cherrypy/cherrypy/lib/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/server/cherrypy/cherrypy/process/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/server/cherrypy/cherrypy/wsgiserver/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/server/static/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/de/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/en/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/en/wordlist/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/en/wordnet/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/en/wordnet/dict/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/en/wordnet/pywordnet/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/es/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/fr/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/it/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/nl/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/text/xx/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/vector/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/vector/svm/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/vector/svm/liblinear-1.93/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/vector/svm/libsvm-3.11/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/vector/svm/libsvm-3.17/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/web/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/web/cache/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/web/docx/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/web/feed/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/web/imap/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/web/json/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/web/locale/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/web/oauth/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/web/pdf/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/web/pdf/cmap/Icon?: Invalid argument
error: unable to create file proj/Sentiment/pattern/web/soup/Icon?: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'`

Bedankt!

**Comment by dqos** [comment]
@witusj

**Comment by dqos** [comment]
Heb het uiteindelijk zelf opgelost, met een on-smart manier.

**Comment by witusj** [comment]
In orde. Laat even weten als je klaar bent. Dan kan ik testen of het bij
mij werkt.

Witek

Op 20 dec. 2017 11:36 a.m. schreef "Qarizma" <notifications@github.com>:
